### ISSUE TITLE
Riemann is required to be running for Kafka to start

### ISSUE THREAD

**Issue by danielcompton** [pingles/kafka-riemann-reporter#1]
I've configured Kafka to use kafka-riemann-reporter to report metrics to Riemann. If I start Kafka without Riemann being available then I get this error and Kafka won't start (the process is running but it's not available for requests).

```
[2014-07-03 03:59:20,250] FATAL  (kafka.Kafka$)
java.lang.RuntimeException: java.io.IOException: Connection failed
    at org.pingles.kafka.KafkaRiemannReporter.initialize(KafkaRiemannReporter.java:38)
    at org.pingles.kafka.KafkaRiemannReporter.init(KafkaRiemannReporter.java:25)
    at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:60)
    at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:58)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
    at kafka.metrics.KafkaMetricsReporter$.startReporters(KafkaMetricsReporter.scala:58)
    at kafka.Kafka$.main(Kafka.scala:36)
    at kafka.Kafka.main(Kafka.scala)
Caused by: java.io.IOException: Connection failed
    at com.aphyr.riemann.client.TcpTransport.connect(TcpTransport.java:143)
...
```

It seems undesirable to have Kafka depending so heavily on a single instance of Riemann being available. Is it possible to have Kafka start without depending on Riemann being available?

**Comment by danielcompton** [comment]
It looks like https://github.com/pingles/kafka-riemann-reporter/blob/master/src/main/java/org/pingles/kafka/KafkaRiemannReporter.java#L38 is where it's happening. Could this be retried on a background thread if it fails?

**Comment by pingles** [comment]
Hi Daniel,

Agree- would be nicer for it to ensure it starts without taking out the broker too. Having said that, it's probably better to change the reporter to push events with UDP instead (although of course means you don't have TCP delivery guarantees).

I'm inclined to switch it to use UDP- would that work for you? It's been a while since I've looked at this but may need to update our production configuration soon anyway so can do it then.

**Comment by danielcompton** [comment]
At first glance I wouldn't be so keen on UDP. From the [Riemann docs](http://riemann.io/howto.html#what-protocol-should-i-use-to-talk-to-riemann) "Use UDP if you intend to have the OS and network discard data automatically, instead of application-level flow control". For us the benefits of UDP wouldn't outweigh the cost of dropping messages and the Riemann docs seem to be pretty clear on using TCP unless there is a good reason not to.

What would make you prefer UDP over TCP?

**Comment by benfleis** [comment]
+1 on TCP connection retries (-1 on UDP) :)

**Comment by pingles** [comment]
Understood, TCP re-connection would be nicer solution overall then. I'd be happy to take a pull request/hand over commit rights :)

**Comment by CVTJNII** [comment]
Based on https://github.com/riemann/riemann-java-client/issues/38 being open I think the Riemann UDP client is broken anyway.  While I agree 100% with TCP being superior I'll accept UDP to avoid creating a potentially very negative dependency.
